version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "dev-school"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"

    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"